// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload():Promise<void>;

export function FetchFiles():Promise<string>;

export function GetDefaultOutputDirectory():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsMac():Promise<boolean>;

export function OpenAuthFileDialog():Promise<string>;

export function OpenInputFileDialog():Promise<string>;

export function OpenOutputDirectoryDialog(arg1:string):Promise<string>;

export function PauseManifest(arg1:string):Promise<void>;

export function ResumeManifest(arg1:string):Promise<void>;

export function RunCLIFetch(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:boolean,arg7:boolean,arg8:string,arg9:string,arg10:number):Promise<string>;

export function ShowDialog():Promise<void>;
