// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function FetchFiles() {
  return window['go']['main']['App']['FetchFiles']();
}

export function GetDefaultOutputDirectory() {
  return window['go']['main']['App']['GetDefaultOutputDirectory']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenInputFileDialog() {
  return window['go']['main']['App']['OpenInputFileDialog']();
}

export function OpenOutputDirectoryDialog() {
  return window['go']['main']['App']['OpenOutputDirectoryDialog']();
}

export function PauseManifest(arg1) {
  return window['go']['main']['App']['PauseManifest'](arg1);
}

export function RunCLIFetch(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['RunCLIFetch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ResumeManifest(arg1) {
  return window['go']['main']['App']['ResumeManifest'](arg1);
}

export function ShowDialog() {
  return window['go']['main']['App']['ShowDialog']();
}
