// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgreeToLicense() {
  return window['go']['main']['App']['AgreeToLicense']();
}

export function CancelAuth(arg1) {
  return window['go']['main']['App']['CancelAuth'](arg1);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DeclineLicense() {
  return window['go']['main']['App']['DeclineLicense']();
}

export function FetchFiles() {
  return window['go']['main']['App']['FetchFiles']();
}

export function FrontendReady() {
  return window['go']['main']['App']['FrontendReady']();
}

export function GetDefaultOutputDirectory() {
  return window['go']['main']['App']['GetDefaultOutputDirectory']();
}

export function GetLatestSupportLogPath() {
  return window['go']['main']['App']['GetLatestSupportLogPath']();
}

export function GetPendingFileOpen() {
  return window['go']['main']['App']['GetPendingFileOpen']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleFileOpen(arg1) {
  return window['go']['main']['App']['HandleFileOpen'](arg1);
}

export function IsMac() {
  return window['go']['main']['App']['IsMac']();
}

export function OpenAuthFileDialog() {
  return window['go']['main']['App']['OpenAuthFileDialog']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenInputFileDialog() {
  return window['go']['main']['App']['OpenInputFileDialog']();
}

export function OpenLogLocation(arg1) {
  return window['go']['main']['App']['OpenLogLocation'](arg1);
}

export function OpenOutputDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenOutputDirectoryDialog'](arg1);
}

export function PauseManifest(arg1) {
  return window['go']['main']['App']['PauseManifest'](arg1);
}

export function ResolveAuth(arg1, arg2) {
  return window['go']['main']['App']['ResolveAuth'](arg1, arg2);
}

export function ResumeManifest(arg1) {
  return window['go']['main']['App']['ResumeManifest'](arg1);
}

export function RunCLIFetch(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['RunCLIFetch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function ShowDialog() {
  return window['go']['main']['App']['ShowDialog']();
}
