// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AgreeToLicense():Promise<void>;

export function CancelAuth(arg1:string):Promise<void>;

export function CancelDownload():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function DeclineLicense():Promise<void>;

export function EmailCurrentLogFile():Promise<void>;

export function FetchFiles():Promise<string>;

export function FrontendReady():Promise<void>;

export function GetDefaultOutputDirectory():Promise<string>;

export function GetPendingFileOpen():Promise<string>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HandleFileOpen(arg1:string):Promise<void>;

export function IsMac():Promise<boolean>;

export function OpenAuthFileDialog():Promise<string>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenInputFileDialog():Promise<string>;

export function OpenOutputDirectoryDialog(arg1:string):Promise<string>;

export function PauseManifest(arg1:string):Promise<void>;

export function ResolveAuth(arg1:string,arg2:string):Promise<void>;

export function ResumeManifest(arg1:string):Promise<void>;

export function RunCLIFetch(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:boolean,arg7:boolean,arg8:string,arg9:string,arg10:boolean,arg11:number):Promise<string>;

export function ShowDialog():Promise<void>;
